# Generated by Django 3.2.16 on 2023-03-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230306_1927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follower_author',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='follower_author'),
        ),
    ]
